### ISSUE TITLE
Allow gusty to ignore some python files

### ISSUE THREAD

**Issue by giuseppellrusso** [pipeline-tools/gusty#66]
While creating a task from a single .py file is just amazing, I think that for more complex tasks it would be very useful to structure your code in a more complex way.

For example, inside my gusty dag folder I would like to have:

- scripts
   - utils.py
- task_1.py -- importing from scripts.utils
- task_2.sql
- task_3.yml 

Right now, if I do something like this a new task utils will be created. Is there already an option or could the parser implement an option to simply skip a file based on some specific header?

**Comment by chriscardillo** [comment]
Thanks @giuseppellrusso.

Would it be reasonable to place `scripts/utils.py` in your Airflow `plugns` folder, so that in `task_1.py`, you call something like:

```python3
from plugins.scripts.utils import my_utility_function
```

Or is this code very specific to this one DAG?

**Comment by giuseppellrusso** [comment]
Hello @chriscardillo, thanks a lot for your fast answer!

I'm currently placing every file that I don't need to be interpreted as a task by gusty in another folder, as you are suggesting. However, this creates a bit of confusion because this code is very specific to this DAG.

To give even more context, we don't only have some utility python module, but we also have some .yaml files needed for storing some configurations. Again, these yaml shouldn't be interpreted as tasks and are currently placed on an external folder. If we try adding them in the gusty folder, it will result in an error 
`AssertionError: No operator specified in yaml spec ...`



Generally speaking, the more complex the dag, the more we would benefit from having the possibility to have python / yaml / any files _inside the gusty dag folder_, but **ignored** from gusty parser. We would benefit in terms of readability and maintenability of the code. 


While facing this, I'm thinking: would it be an easy win to have the possibility to specify a subfolder name which gusty will simply ignore when parsing the files (instead of considering it as a task group)?

**Comment by chriscardillo** [comment]
If you are using `create_dag`, one option for you is to use the [`ignore_subfolders`](https://pipeline-tools.github.io/gusty-docs/create-dag-args.html#ignore_subfolders) argument.

By setting `ignore_subfolders=True`, gusty would ignore all subfolders in the dag.

Curious, though, are you using some subfolders for task groups, though?

**Comment by chriscardillo** [comment]
@giuseppellrusso - I just released [v0.22.0](https://github.com/pipeline-tools/gusty/releases/tag/v0.22.0) which will allow you to ignore specific subfolders by adding a file called `.gustyignore`. You can read about ignoring subfolders [here](https://pipeline-tools.github.io/gusty-docs/task-groups.html#ignoring-subfolders).

Now you are able to either: 
- Ignore all subfolders with the `ignore_subfolders` argument
- Ignore subfolders of your choosing by adding a `.gustyignore` file those specific subfolders

Thanks for raising your issue. I will close this as completed, but if you have any other questions on this please feel free to reopen.

**Comment by giuseppellrusso** [comment]
@chriscardillo thanks a lot for your dedication, your solution is actually working like a charm!

Yes, there are cases in which we could be using some subfolders for task groups and still wanting some subfolder to be used just to better organize the structure of the code, and .gustyignore will perfectly fit this use case! 👍
